In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [17]:
df = pd.read_csv("solar_system.csv")
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [18]:
print(df.shape)

(20, 11)

In [21]:
df = df.set_index("Attribute").T  #tells our computer to index through the dataframe with the "attribute" ROWS
df.index.name = "Planet"    #changes the name of the index to "Planets" which is why there is an error message saying the name "attributes" no longer exists in my columns
df.reset_index(inplace=True)        #Resets the index to og columns without changing any data, but now the rows and columns switch places
df.columns.name = None              #the column name changes stay so "planets" is now where "attribute" was, but now "planets" is just a name

KeyError: "None of ['Attribute'] are in the columns"

In [13]:
df.shape    #shape previously (20 rows, 11 columns) now (10 rows, 21 columns)

(10, 21)

In [22]:
#The new shape is not (11,20) because the previous row of "planets... names" with all the planet names are not considered a new column to index through (just a label for the data)
print(df.columns)

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [23]:
#16 columns have units ('Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       # 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       # 'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       # 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       # 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)','Obliquity to Orbit (deg)',
       # 'Mean Temperature (C)', 'Surface Pressure (bars)')
#5 columns do not have units ('Planet', 'Orbital Eccentricity', 'Number of Moons',
       # 'Ring System?', 'Global Magnetic Field?')

df

In [25]:
#2.1.2 --- Investiage Data Types ---

In [26]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [29]:
for col in df:
    print(df[col].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [30]:
#The actual values are actually all strings
#It just makes data analysis more steps because the string data would have to be converted to integers first if we wanted to work with the numbers

In [31]:
#2.1.3 --- Convert Strings to Numbers ---

In [40]:
pd.to_numeric(df['Mass (10^24kg)'], errors='coerce')

0       0.330
1       4.870
2       5.970
3       0.073
4       0.642
5    1898.000
6     568.000
7      86.800
8     102.000
9       0.013
Name: Mass (10^24kg), dtype: float64

In [41]:
pd.to_numeric(df['Diameter (km)'], errors='coerce')

0      4879
1     12104
2     12756
3      3475
4      6792
5    142984
6    120536
7     51118
8     49528
9      2376
Name: Diameter (km), dtype: int64

In [42]:
pd.to_numeric(df['Density (kg/m^3)'], errors='coerce')

0    5429
1    5243
2    5514
3    3340
4    3934
5    1326
6     687
7    1270
8    1638
9    1850
Name: Density (kg/m^3), dtype: int64

In [43]:
pd.to_numeric(df['Gravity (m/s^2)'], errors='coerce')

0     3.7
1     8.9
2     9.8
3     1.6
4     3.7
5    23.1
6     9.0
7     8.7
8    11.0
9     0.7
Name: Gravity (m/s^2), dtype: float64

In [44]:
pd.to_numeric(df['Escape Velocity (km/s)'], errors='coerce')

0     4.3
1    10.4
2    11.2
3     2.4
4     5.0
5    59.5
6    35.5
7    21.3
8    23.5
9     1.3
Name: Escape Velocity (km/s), dtype: float64

In [45]:
pd.to_numeric(df['Rotation Period (hours)'], errors='coerce')

0    1407.6
1   -5832.5
2      23.9
3     655.7
4      24.6
5       9.9
6      10.7
7     -17.2
8      16.1
9    -153.3
Name: Rotation Period (hours), dtype: float64

In [46]:
pd.to_numeric(df['Length of Day (hours)'], errors='coerce')

0    4222.6
1    2802.0
2      24.0
3     708.7
4      24.7
5       9.9
6      10.7
7      17.2
8      16.1
9     153.3
Name: Length of Day (hours), dtype: float64

In [47]:
pd.to_numeric(df['Distance from Sun (10^6 km)'], errors='coerce')

0      57.900
1     108.200
2     149.600
3       0.384
4     228.000
5     778.500
6    1432.000
7    2867.000
8    4515.000
9    5906.400
Name: Distance from Sun (10^6 km), dtype: float64

In [48]:
pd.to_numeric(df['Perihelion (10^6 km)'], errors='coerce')

0      46.000
1     107.500
2     147.100
3       0.363
4     206.700
5     740.600
6    1357.600
7    2732.700
8    4471.100
9    4436.800
Name: Perihelion (10^6 km), dtype: float64

In [49]:
pd.to_numeric(df['Orbital Period (days)'], errors='coerce')

0       88.0
1      224.7
2      365.2
3       27.3
4      687.0
5     4331.0
6    10747.0
7    30589.0
8    59800.0
9    90560.0
Name: Orbital Period (days), dtype: float64

In [50]:
pd.to_numeric(df['Orbital Velocity (km/s)'], errors='coerce')

0    47.4
1    35.0
2    29.8
3     1.0
4    24.1
5    13.1
6     9.7
7     6.8
8     5.4
9     4.7
Name: Orbital Velocity (km/s), dtype: float64

In [51]:
pd.to_numeric(df['Orbital Inclination (deg)'], errors='coerce')

0     7.0
1     3.4
2     0.0
3     5.1
4     1.8
5     1.3
6     2.5
7     0.8
8     1.8
9    17.2
Name: Orbital Inclination (deg), dtype: float64

In [52]:
pd.to_numeric(df['Orbital Eccentricity'], errors='coerce')

0    0.206
1    0.007
2    0.017
3    0.055
4    0.094
5    0.049
6    0.052
7    0.047
8    0.010
9    0.244
Name: Orbital Eccentricity, dtype: float64

In [53]:
pd.to_numeric(df['Obliquity to Orbit (deg)'], errors='coerce')

0      0.034
1    177.400
2     23.400
3      6.700
4     25.200
5      3.100
6     26.700
7     97.800
8     28.300
9    119.500
Name: Obliquity to Orbit (deg), dtype: float64

In [54]:
pd.to_numeric(df['Mean Temperature (C)'], errors='coerce')

0    167
1    464
2     15
3    -20
4    -65
5   -110
6   -140
7   -195
8   -200
9   -225
Name: Mean Temperature (C), dtype: int64

In [55]:
pd.to_numeric(df['Surface Pressure (bars)'], errors='coerce')

0     0.00000
1    92.00000
2     1.00000
3     0.00000
4     0.01000
5         NaN
6         NaN
7         NaN
8         NaN
9     0.00001
Name: Surface Pressure (bars), dtype: float64

In [56]:
pd.to_numeric(df['Number of Moons'], errors='coerce')

0      0
1      0
2      1
3      0
4      2
5     95
6    274
7     28
8     16
9      5
Name: Number of Moons, dtype: int64

In [60]:
for col in df:
    if col != "Planet" and col != "Ring System?" and col != "Global Magnetic Field?":
        df[col] = pd.to_numeric(df[col], errors = "coerce")      #isolates the columns we want to change
for col in df:
    print(df[col].apply(type))           #prints diff dtypes

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Mass (10^24kg), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Diameter (km), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Density (kg/m^3), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Gravity (m/s^2), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Rotation Period (hours), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Length of Day (hours), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Period (days), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Eccentricity, dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Mean Temperature (C), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Surface Pressure (bars), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [62]:
#The three different dtypes now in df are strings, floats, and integers
# 'str' = string (a word), 'float64' = float (decimals), 'int64' = integer (whole number)
# Only the column name labels are objects because they are not numerical or word data.

In [63]:
#2.2 --- Apply Astropy Units ---

In [79]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0 d2,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7 d2,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2 d2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3 d2,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0 d2,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0 d2,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0 d2,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0 d2,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0 d2,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0 d2,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [65]:
def attach_units(col):
    units = 10**6 * u.km
    data = []
    for val in df[col]:
        data.append(val*units)
    df[col] = data
#favorite column "Distance from Sun"
attach_units("Distance from Sun (10^6 km)")
print(df["Distance from Sun (10^6 km)"])

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384000.0 km
4     228000000.0 km
5     778500000.0 km
6    1432000000.0 km
7    2867000000.0 km
8    4515000000.0 km
9    5906400000.0 km
Name: Distance from Sun (10^6 km), dtype: object

In [66]:
#2.3 --- Data Analysis ---

In [67]:
     #1 Semi-Major Axis

In [68]:
semi_major = (df['Perihelion (10^6 km)'] + df['Aphelion (10^6 km)'])/2
df.insert(11,"Semi-Major Axis (10^6 km)", semi_major)
print(df["Semi-Major Axis (10^6 km)"])

0      57.9000
1     108.2000
2     149.6000
3       0.3845
4     228.0000
5     778.5000
6    1432.0500
7    2867.0500
8    4515.0000
9    5906.3500
Name: Semi-Major Axis (10^6 km), dtype: float64

In [69]:
      #2 Convert Orbital Period to Years

In [80]:
print(df['Orbital Period (days)'])

0       88.0 d2
1      224.7 d2
2      365.2 d2
3       27.3 d2
4      687.0 d2
5     4331.0 d2
6    10747.0 d2
7    30589.0 d2
8    59800.0 d2
9    90560.0 d2
Name: Orbital Period (days), dtype: object

In [77]:
# def attach_units2(col):
#     units = u.day
#     data = []
#     for val in df[col]:
#         data.append(val*units)
#     df[col] = data
# attach_units2('Orbital Period (days)')
# print(df['Orbital Period (days)'])

In [78]:
print(df['Orbital Period (days)'])

0       88.0 d2
1      224.7 d2
2      365.2 d2
3       27.3 d2
4      687.0 d2
5     4331.0 d2
6    10747.0 d2
7    30589.0 d2
8    59800.0 d2
9    90560.0 d2
Name: Orbital Period (days), dtype: object

In [82]:
data=[]
for val in df['Orbital Period (days)']:
    units = (val/365)*u.year
    data.append(units)
df['Orbital Period (days)'] = data

print(df['Orbital Period (days)'])

0    0.2410958904109589 d2 yr
1    0.6156164383561643 d2 yr
2    1.0005479452054795 d2 yr
3    0.0747945205479452 d2 yr
4    1.8821917808219177 d2 yr
5    11.865753424657534 d2 yr
6    29.443835616438356 d2 yr
7      83.8054794520548 d2 yr
8    163.83561643835617 d2 yr
9     248.1095890410959 d2 yr
Name: Orbital Period (days), dtype: object

In [83]:
df.rename(columns = {"Orbital Period (days)": "Orbital Period (years)"}, inplace=True)
print(df.loc[0])
print(df["Orbital Period (years)"])

Planet                                          Mercury
Mass (10^24kg)                                     0.33
Diameter (km)                                      4879
Density (kg/m^3)                                   5429
Gravity (m/s^2)                                     3.7
Escape Velocity (km/s)                              4.3
Rotation Period (hours)                          1407.6
Length of Day (hours)                            4222.6
Distance from Sun (10^6 km)               57900000.0 km
Perihelion (10^6 km)                               46.0
Aphelion (10^6 km)                                 69.8
Semi-Major Axis (10^6 km)                          57.9
Orbital Period (years)         0.2410958904109589 d2 yr
Orbital Velocity (km/s)                            47.4
Orbital Inclination (deg)                           7.0
Orbital Eccentricity                              0.206
Obliquity to Orbit (deg)                          0.034
Mean Temperature (C)                                167
Surface Pressure (bars)                             0.0
Number of Moons                                       0
Ring System?                                         No
Global Magnetic Field?                              Yes
Name: 0, dtype: object
0    0.2410958904109589 d2 yr
1    0.6156164383561643 d2 yr
2    1.0005479452054795 d2 yr
3    0.0747945205479452 d2 yr
4    1.8821917808219177 d2 yr
5    11.865753424657534 d2 yr
6    29.443835616438356 d2 yr
7      83.8054794520548 d2 yr
8    163.83561643835617 d2 yr
9     248.1095890410959 d2 yr
Name: Orbital Period (years), dtype: object

In [84]:
print(f"Mars has an orbital period of {df["Orbital Period (years)"][4]:.4f}")  #don't mind the d2 lol idrk why its stuck there

Mars has an orbital period of 1.8822 d2 yr

In [85]:
    #Convert Distance Columns (km --> AU)
#AU stands for astronomical unit and is the average distance between Earth and our sun.
print(const.au)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [87]:
au_km = const.au.to(u.km)
print(au_km)

149597870.70000002 km

In [88]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,0.2410958904109589 d2 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,0.6156164383561643 d2 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,1.0005479452054795 d2 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,0.0747945205479452 d2 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,1.8821917808219177 d2 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,11.865753424657534 d2 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,29.443835616438356 d2 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,83.8054794520548 d2 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,163.83561643835617 d2 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,248.1095890410959 d2 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [91]:
#columns to convert to AU: Diameter (km), Distance from Sun (10^6 km), Perihelion (10^6 km), Aphelion (10^6 km), Semi-Major Axis (10^6 km)

In [98]:
kmcolumns = ['Diameter (km)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Semi-Major Axis (10^6 km)']
for col in kmcolumns:
    newdata = []
    if col != "Diameter (km)":
        for val in df[col]:
            units = (val*10**6/(149597870.70000002))*u.AU      #10^6 km to AU
            newdata.append(units)
        df[col] = newdata
    else:
        for val in df[col]:
            units = (val/(149597870.70000002))*u.AU      #km to AU
            newdata.append(units)
        df[col] = newdata
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4.352772637883371e-40 AU6,5429,3.7,4.3,1407.6,4222.6,0.0007727502256148896 AU5 km,9.1842526138288e-08 AU4,...,0.2410958904109589 d2 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,1.0798516091194982e-39 AU6,5243,8.9,10.4,-5832.5,2802.0,0.0014440686426862013 AU5 km,2.146319904318687e-07 AU4,...,0.6156164383561643 d2 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,1.1380194254732583e-39 AU6,5514,9.8,11.2,23.9,24.0,0.0019966050734367435 AU5 km,2.9369642597700363e-07 AU4,...,1.0005479452054795 d2 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3.1002018685477988e-40 AU6,3340,1.6,2.4,655.7,708.7,5.1249755895702526e-06 AU5 km,7.247573258304032e-10 AU4,...,0.0747945205479452 d2 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6.059444918324218e-40 AU6,3934,3.7,5.0,24.6,24.7,0.0030429542563073365 AU5 km,4.1269239462574196e-07 AU4,...,1.8821917808219177 d2 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,1.2756237812156506e-38 AU6,1326,23.1,59.5,9.9,9.9,0.010390087230417814 AU5 km,1.4786646708264372e-06 AU4,...,11.865753424657534 d2 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,1.0753552012295755e-38 AU6,687,9.0,35.5,10.7,10.7,0.01911188813610573 AU5 km,2.710552467072604e-06 AU4,...,29.443835616438356 d2 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,4.560463859465509e-39 AU6,1270,8.7,21.3,-17.2,17.2,0.038263815144004974 AU5 km,5.4560450256108625e-06 AU4,...,83.8054794520548 d2 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,4.4186128962715215e-39 AU6,1638,11.0,23.5,16.1,16.1,0.06025850204924398 AU5 km,8.926893882976076e-06 AU4,...,163.83561643835617 d2 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2.119735148106351e-40 AU6,1850,0.7,1.3,-153.3,153.3,0.07882853078707742 AU5 km,8.858411303703395e-06 AU4,...,248.1095890410959 d2 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [99]:
df.rename(columns = {"Diameter (km)": "Diameter (AU)"}, inplace=True)
df.rename(columns = {"Distance from Sun (10^6 km)": "Distance from Sun (AU)"}, inplace=True)
df.rename(columns = {"Perihelion (10^6 km)": "Perihelion (AU)"}, inplace=True)
df.rename(columns = {"Aphelion (10^6 km)": "Aphelion (AU)"}, inplace=True)
df.rename(columns = {"Semi-Major Axis (10^6 km)": "Semi-Major Axis (AU)"}, inplace=True)

In [100]:
print(df["Diameter (AU)"][4])
print(df["Distance from Sun (AU)"][4])
print(df["Perihelion (AU)"][4])
print(df["Aphelion (AU)"][4])
print(df["Semi-Major Axis (AU)"][4])        #converted values of MARS

6.059444918324218e-40 AU6
0.0030429542563073365 AU5 km
4.1269239462574196e-07 AU4
7.446182554465755e-05 AU3
0.010187739731799502 AU2

In [101]:
#no bonus sorry

In [102]:
#2.4 --- Save Your Results ---

In [103]:
df.to_csv("units.csv", index=False)